{"name": "Проверка кода API на ошибку логинизации при неправильном пароле", "status": "passed", "start": 1712696808772, "stop": 1712696808848, "uuid": "bf9c99e6-6a7f-4fb3-8b43-1f9a9ddd33de", "historyId": "6e590d0e542af5ff0782d3224574bf94", "testCaseId": "6e590d0e542af5ff0782d3224574bf94", "fullName": "tests.test_login.TestLogin#test_wrong_login_password_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "maksimka"}, {"name": "thread", "value": "49960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}